name: flutter_blue_plus_linux
description: Linux implementation of the flutter_blue_plus plugin.
version: 2.0.1
homepage: https://github.com/tnc1997/flutter-blue-plus

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  bluez: '>=0.7.8 <0.9.0'
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface:
    path: ../flutter_blue_plus_platform_interface
  rxdart: '>=0.27.0 <0.29.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      linux:
        dartPluginClass: FlutterBluePlusLinux
