name: flutter_blue_plus_web
description: Web implementation of the flutter_blue_plus plugin.
version: 2.0.1
homepage: https://github.com/tnc1997/flutter-blue-plus

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_platform_interface:
    path: ../flutter_blue_plus_platform_interface
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: flutter_blue_plus
    platforms:
      web:
        pluginClass: FlutterBluePlusWeb
        fileName: flutter_blue_plus_web.dart
